FROM jenkins/jenkins:lts

# Skip Docker installation and permissions adjustment

# Optional: Set Jenkins to run without the setup wizard
ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false"

# Install necessary Jenkins plugins
RUN jenkins-plugin-cli --plugins \
    git \
    workflow-aggregator \
    docker-workflow \
    blueocean \
    credentials-binding \
    pipeline-utility-steps

# Set default Jenkins user credentials
ENV JENKINS_USER admin
ENV JENKINS_PASS admin

# Expose necessary ports
EXPOSE 8080
EXPOSE 50000
